type t = LIMIT | MARKET | STOP_LOSS | STOP_LOSS_LIMIT 
                 | TAKE_PROFIT | TAKE_PROFIT_LIMIT | LIMIT_MAKER;;

let wrap = function
  |LIMIT -> "LIMIT"
  |MARKET -> "MARKET"
  |STOP_LOSS -> "STOP_LOSS"
  |STOP_LOSS_LIMIT -> "STOP_LOSS_LIMIT"
  |TAKE_PROFIT -> "TAKE_PROFIT"
  |TAKE_PROFIT_LIMIT -> "TAKE_PROFIT_LIMIT"
  |LIMIT_MAKER -> "LIMIT_MAKER";;

let unwrap =  function
  |"LIMIT" -> LIMIT
  |"MARKET" -> MARKET
  |"STOP_LOSS" -> STOP_LOSS
  |"STOP_LOSS_LIMIT" -> STOP_LOSS_LIMIT
  |"TAKE_PROFIT" -> TAKE_PROFIT
  |"TAKE_PROFIT_LIMIT" -> TAKE_PROFIT_LIMIT
  |"LIMIT_MAKER" -> LIMIT_MAKER
  |_ -> raise Not_found;;