module Klines_test = Klines_test
module Older_trade_lookup_test = Older_trade_lookup_test
module Order_book_test = Order_book_test
module Recent_trade_list_test = Recent_trade_list_test
module Server_time_test = Server_time_test
module Symbol_price_ticker_test = Symbol_price_ticker_test
module Test_connectivity_test = Test_connectivity_test